### ISSUE TITLE
Value storage out of bounds for mixed variable types

### ISSUE THREAD

**Issue by schteppe** [mtiller/fmusdk#3]
Hi,
I've been fiddling with your lib to build an own co-simulation FMU, and I just realized that things get messy when mixing different kinds of variables in the same model.

A thing that I've assumed this far is that a value reference is unique throughout the model, no matter what type the variable it is referencing. (Correct me here if I'm wrong.)

That said, I think the in-memory storage mechanism for model variables needs to be modified.
Let's say I have 1 real and 1 integer to store. This is how the storage is allocated:

```
comp->r = calloc(NUMBER_OF_REALS,    sizeof(fmiReal));
comp->i = calloc(NUMBER_OF_INTEGERS, sizeof(fmiInteger));
```

...where each of those macros are defined to be 1.
I naturally pick the value references to 0 and 1 for my two variables. When trying to set the value of the variable with value reference = 1, I get "fmiSetInteger: Illegal value reference 1", This is because we can't store the integer at the second position in the allocated array of length 1:

```
comp->i[vr[i]] = value[i]; // vr[i] == 1
```

I find this inconsistent.

Thanks for all your great work.
Stefan

**Comment by mtiller** [comment]
@schteppe 

  I should point out several things here.  First, I didn't write any of this code (I only made a Linux port).  Second, I'm only peripherally involved in the FMI development process.  I'm mainly a consumer of FMI, not a developer.

  Now, given all that it seems to me that your comments are really about the FMI specification (and how reference values are used).  So for that, you should consult the [FMI specification](http://www.fmi-standard.org) itself.  I would also point out that I don't really use the FMUSDK anymore.  It was simply an initial attempt (by others) to create something that could simulate FMUs (under Windows) as an aid to design and development of the specification.  A much more recent effort is the [FMI Library](http://www.jmodelica.org/FMILibrary) and a Python extension, [PyFMI](http://www.jmodelica.org/page/4924) that can be used in conjumption with that.  Modelon maintains [a GitHub mirror](https://github.com/modelon/PyFMI) of the PyFMI repository here on GitHub.

  Honestly, you will have to consult the FMI specification to confirm whether your understanding of the reference values is correct.  And I would strongly encourage you to use FMI Library and to report any inconsistencies between the specification and that implementation to the developers.

  I hope that helps.

**Comment by schteppe** [comment]
Oh, this was embarrassing. Sorry. I'll send my rants to the devs that need them instead.
Anyway, thanks for the port. I've gotten use of it for some of my FMU development.

Stefan

**Comment by mtiller** [comment]
No problem.  I can see where it would be confusing.
